### ISSUE TITLE
Roadmap to V1.0

### ISSUE THREAD

**Issue by cvigilv** [cvigilv/esqueleto.nvim#4]
Issue to add all other issues related to V1.0

**Comment by cvigilv** [comment]
- [ ] Cleaner template storage using Vim ftplugin directory style
- [x] Template insertion in empty files
- [x] On-demand template insertion
- [ ] Template creation interface
- [ ] Handle multiple template folders
- [ ] Proyect specific templates
- [ ] Template preview via Telescope
- [ ] User customizable prompt and insertion rules

**Comment by cvigilv** [comment]
Created milestone
